version: '2'

services:
  backend:
    build: ./backend
    command: >
      gunicorn -b 0.0.0.0:5000
        --access-logfile -
        --reload
        "backend.app:create_app()"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/backend'  
    ports:
      - '5000:5000'
    
    
  frontend:
    build: ./client
    working_dir: /client
    command: 'npm start'
    stdin_open: true
    ports: 
      - '3000:3000'

